service: githubaction-lambda-session

provider:
  name: aws
  runtime: nodejs14.x
  stage: main
  region: us-east-1

functions:
  BJIT:
    handler: handler.generateRandomNumber
    timeout: 60 # seconds
    memorySize: 128 # mb